language: rust

rust:
  - stable
  - beta
  - nightly

cache: cargo

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_script:
  - if [[ $TRAVIS_RUST_VERSION == 'nightly' ]]; then rustup component add rustfmt --toolchain nightly; fi 

script:
  - cargo test
  - if [[ $TRAVIS_RUST_VERSION == 'nightly' ]]; then cargo +nightly fmt --all -- --check; fi
